[package]
name = "sparse_rulers_rust"
version = "0.8.0"
edition = "2024"

[dependencies]
chrono = "0.4.44"
clap = { version = "4.5.31", features = ["derive"] }
ctrlc = "3.5.2"
fixedbitset = "0.5.7"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
cpu-time = "1.0.0"
indicatif = "0.18.4"
